import { test, expect, openFilterGroup } from './radar-fixture';

for (const language of ['en', 'nl']) {
  test(`filter accordion stays compact and exposes active choices in ${language}`, async ({ page, isMobile }, testInfo) => {
    if (isMobile) await page.setViewportSize({ width: 360, height: 780 });
    await page.addInitScript((language) => localStorage.setItem('vector.language', language), language);
    await page.goto('/');
    await expect(page.locator('.aircraft-map-marker')).toHaveCount(2);
    if (isMobile) await page.locator('.mobile-list-button').click();
    const map = (await page.locator('.maplibre-surface').boundingBox())!;
    await page.locator('.filter-menu > summary').click();
    const filter = page.locator('.filter-popover');
    const groups = filter.locator('.filter-group');
    await expect(groups).toHaveCount(5);
    await expect(filter.locator('.filter-group[open]')).toHaveCount(0);
    const initial = (await filter.boundingBox())!;
    expect(initial.height).toBeLessThan(480);
    expect(await filter.evaluate((element) => element.scrollHeight <= element.clientHeight)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath(`compact-menu-${language}.png`) });

    const category = filter.locator('[data-filter-group="categories"]');
    const flight = filter.locator('[data-filter-group="flight"]');
    await category.locator('summary').press('Enter');
    await expect(category).toHaveAttribute('open', '');
    await category.getByLabel(language === 'nl' ? 'Ballon / luchtschip' : 'Balloon / airship', { exact: true }).check();
    await flight.locator('summary').press('Space');
    await expect(category).not.toHaveAttribute('open');
    await expect(flight).toHaveAttribute('open', '');
    await expect(filter.locator('.filter-group[open]')).toHaveCount(1);
    await expect(category.locator('summary')).toContainText(language === 'nl' ? 'Ballon / luchtschip' : 'Balloon / airship');
    await expect(category).toHaveClass(/has-filters/);
    const altitude = flight.getByRole('spinbutton', { name: language === 'nl' ? 'Hoogte · Tot (m)' : 'Altitude · To (m)', exact: true });
    await altitude.fill('1000');
    await altitude.press('Tab');
    await flight.locator('summary').press('Enter');
    await expect(filter.locator('.filter-group[open]')).toHaveCount(0);
    await expect(flight.locator('summary')).toContainText(language === 'nl' ? 'Hoogte ≤ 1.000 m' : 'Altitude ≤ 1,000 m');
    await expect(filter.getByRole('status')).toContainText('1');
    await expect(page.locator('.aircraft-map-marker')).toHaveCount(1);
    expect((await page.locator('.maplibre-surface').boundingBox())!).toEqual(map);
    await page.screenshot({ path: testInfo.outputPath(`active-menu-${language}.png`) });

    await filter.locator('.filter-reset').click();
    await expect(filter.locator('.filter-group.has-filters')).toHaveCount(0);
    await expect(flight.locator('summary')).toContainText(language === 'nl' ? 'Onbeperkt' : 'Unlimited');
    await expect(page.locator('.aircraft-map-marker')).toHaveCount(2);
    await page.keyboard.press('Escape');
    await expect(filter).not.toBeVisible();
    await expect(page.locator('.filter-menu > summary')).toBeFocused();
    await page.locator('.filter-menu > summary').click();
    await page.locator('.brand').click();
    await expect(filter).not.toBeVisible();
    expect((await page.locator('.maplibre-surface').boundingBox())!).toEqual(map);
  });
}

test('combined filters, ranges, saved views and units remain consistent', async ({ page, isMobile }, testInfo) => {
  if (isMobile) await page.setViewportSize({ width: 360, height: 780 });
  await page.goto('/');
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(2);
  if (isMobile) await page.locator('.mobile-list-button').click();
  await page.locator('.filter-menu > summary').click();
  const filter = page.locator('.filter-popover');
  await page.screenshot({ path: testInfo.outputPath('filter-menu.png') });
  const categories = filter.locator('.filter-categories');
  await openFilterGroup(page, 'categories');
  await categories.getByLabel('Balloon / airship', { exact: true }).check();
  await expect(page.locator('.aircraft-row')).toHaveCount(1);
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(1);
  await categories.getByLabel('Airliner', { exact: true }).check();
  await expect(page.locator('.aircraft-row')).toHaveCount(2);
  await openFilterGroup(page, 'flight');
  const minAltitude = filter.getByRole('spinbutton', { name: 'Altitude · From (m)', exact: true });
  const maxAltitude = filter.getByRole('spinbutton', { name: 'Altitude · To (m)', exact: true });
  await minAltitude.fill('1000');
  await minAltitude.press('Tab');
  await expect(maxAltitude).toBeFocused();
  await expect(page.locator('.aircraft-row')).toHaveCount(1);
  await expect(page.locator('.aircraft-row')).toContainText('VECTOR');
  await maxAltitude.fill('500');
  await maxAltitude.press('Tab');
  await expect(maxAltitude).toHaveAttribute('aria-invalid', 'true');
  await expect(page.locator('.aircraft-row')).toHaveCount(1);
  // Accordion navigation preserves invalid drafts without applying them.
  await openFilterGroup(page, 'distance');
  await expect(filter.locator('[data-filter-group="flight"] > summary')).toContainText('Altitude ≥ 1,000 m');
  await openFilterGroup(page, 'flight');
  await expect(maxAltitude).toHaveValue('500');
  await expect(maxAltitude).toHaveAttribute('aria-invalid', 'true');
  await maxAltitude.fill('7000');
  await maxAltitude.press('Tab');
  await expect(maxAltitude).toHaveAttribute('aria-invalid', 'false');
  const speed = filter.getByRole('spinbutton', { name: 'Ground speed · From (km/h)', exact: true });
  await speed.fill('100');
  await speed.press('Tab');
  await openFilterGroup(page, 'distance');
  await filter.getByRole('combobox', { name: 'Distance from receiver', exact: true }).selectOption('25');
  await expect(page.locator('.active-filter-chip')).toHaveCount(4);
  await expect(filter.getByRole('status')).toContainText('1 aircraft match');
  await openFilterGroup(page, 'presets');
  await filter.getByRole('button', { name: 'Save current', exact: true }).click();
  await filter.getByRole('textbox', { name: 'Saved view name', exact: true }).fill('Nearby aircraft');
  await filter.getByRole('button', { name: 'Save', exact: true }).click();
  await filter.getByRole('button', { name: 'Rename view: Nearby aircraft', exact: true }).click();
  await expect(filter).toBeVisible();
  await filter.getByRole('textbox', { name: 'Saved view name', exact: true }).fill('Local aircraft');
  await filter.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(filter.locator('[data-filter-group="presets"] > summary')).toContainText('Local aircraft');
  const physicalFilters = await page.evaluate(() => JSON.parse(localStorage.getItem('vector.aircraftFilters')!));
  await filter.locator('.filter-reset').click();
  await expect(page.locator('.aircraft-row')).toHaveCount(2);
  await filter.locator('.filter-preset-apply').click();
  await expect(page.locator('.aircraft-row')).toHaveCount(1);
  await page.keyboard.press('Escape');
  await expect(filter).not.toBeVisible();
  await expect(page.locator('.filter-menu > summary')).toBeFocused();

  await page.locator('.settings-menu summary').click();
  await page.getByRole('combobox', { name: 'Unit system', exact: true }).selectOption('aeronautical');
  await page.keyboard.press('Escape');
  await page.locator('.filter-menu > summary').click();
  await openFilterGroup(page, 'flight');
  const altitudeFt = filter.getByRole('spinbutton', { name: 'Altitude · From (ft)', exact: true });
  await expect(altitudeFt).toHaveValue('3280.84');
  await altitudeFt.focus();
  await altitudeFt.press('Tab');
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('vector.aircraftFilters')!))).toEqual(physicalFilters);
  await page.screenshot({ path: testInfo.outputPath('expanded-filters.png') });
  const bounds = (await filter.boundingBox())!;
  expect(bounds.x).toBeGreaterThanOrEqual(0);
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(page.viewportSize()!.width);
  expect(bounds.y + bounds.height).toBeLessThanOrEqual(page.viewportSize()!.height);
  expect(await filter.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.reload();
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(1);
  if (isMobile) await page.locator('.mobile-list-button').click();
  await expect(page.locator('.active-filter-chip')).toHaveCount(4);
  await page.locator('.filter-menu > summary').click();
  await expect(filter.locator('[data-filter-group="flight"] > summary')).toContainText('Altitude 3,280.8–22,965.9 ft');
  await openFilterGroup(page, 'flight');
  await expect(filter.getByRole('spinbutton', { name: 'Altitude · From (ft)', exact: true })).toHaveValue('3280.84');
});

test('advanced filters exclude the selected aircraft without losing its details', async ({ page, isMobile }) => {
  await page.goto('/');
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(2);
  if (isMobile) await page.locator('.mobile-list-button').click();
  await page.locator('.aircraft-row').filter({ hasText: 'VECTOR' }).click();
  if (isMobile) await page.locator('.mobile-list-button').click();
  await page.locator('.filter-menu > summary').click();
  await openFilterGroup(page, 'advanced');
  const filter = page.locator('.filter-popover');
  const type = filter.getByRole('textbox', { name: /ICAO type codes/ });
  await type.fill('BALL');
  await type.press('Tab');
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(1);
  await expect(page.locator('.aircraft-map-marker')).toContainText('BALLOON');
  await expect(page.locator('.aircraft-row')).toHaveCount(1);
  if (!isMobile) await expect(page.locator('.flight-title')).toContainText('VECTOR');
  await type.fill('B738, invalid-type');
  await type.press('Tab');
  await expect(type).toHaveAttribute('aria-invalid', 'true');
  await expect(page.locator('.aircraft-row')).toHaveCount(1);
  await type.fill('');
  await type.press('Tab');
  await filter.getByRole('combobox', { name: 'Source', exact: true }).selectOption('mlat');
  await expect(page.locator('.aircraft-row')).toHaveCount(0);
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(0);
  await filter.getByRole('combobox', { name: 'Source', exact: true }).selectOption('all');
  await filter.getByRole('combobox', { name: 'Position', exact: true }).selectOption('without');
  await expect(page.locator('.aircraft-row')).toHaveCount(0);
  await filter.locator('.filter-reset').click();
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(2);
  // Closing outside must not resize the list/map or consume the next pointer action.
  const map = (await page.locator('.maplibre-surface').boundingBox())!;
  await page.locator('.brand').click();
  await expect(filter).not.toBeVisible();
  expect((await page.locator('.maplibre-surface').boundingBox())!).toEqual(map);
});

test('category and altitude filters also apply to receiver history', async ({ page, radar, isMobile }) => {
  const now = new Date('2026-01-15T12:32:00Z');
  await page.clock.setFixedTime(now);
  radar.timestamp = now.getTime() / 1000;
  await page.goto('/');
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(2);
  if (isMobile) await page.locator('.mobile-list-button').click();
  await page.locator('.filter-menu > summary').click();
  await openFilterGroup(page, 'categories');
  await page.locator('.filter-categories').getByLabel('Balloon / airship', { exact: true }).check();
  await openFilterGroup(page, 'flight');
  const altitude = page.getByRole('spinbutton', { name: 'Altitude · To (m)', exact: true });
  await altitude.fill('1000');
  await altitude.press('Tab');
  await page.keyboard.press('Escape');
  if (isMobile) await page.locator('.mobile-sheet-close').click();
  await page.getByRole('button', { name: 'History', exact: true }).click();
  await expect(page.getByRole('slider', { name: 'History timeline' })).toBeEnabled();
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(1);
  await expect(page.locator('.aircraft-row')).toContainText('BALL');
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(1);
});

test('distance requires a receiver position and accepts a custom radius', async ({ page, radar, isMobile }) => {
  radar.receiverPositionKnown = false;
  await page.goto('/');
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(2);
  if (isMobile) await page.locator('.mobile-list-button').click();
  await page.locator('.filter-menu > summary').click();
  await openFilterGroup(page, 'distance');
  const distance = page.getByRole('combobox', { name: 'Distance from receiver', exact: true });
  await distance.selectOption('25');
  await expect(page.locator('.filter-warning')).toContainText('Receiver location is unknown');
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(0);
  await expect(page.locator('.aircraft-row')).toHaveCount(0);
  await distance.selectOption('');
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(2);
  await distance.selectOption('custom');
  const radius = page.getByRole('spinbutton', { name: 'Distance from receiver · To (km)', exact: true });
  await radius.fill('5');
  await radius.press('Tab');
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(0);
  radar.receiverPositionKnown = true;
  await page.reload();
  await expect(page.locator('.aircraft-map-marker')).toHaveCount(1);
  if (isMobile) await page.locator('.mobile-list-button').click();
  await page.locator('.filter-menu > summary').click();
  await openFilterGroup(page, 'distance');
  await expect(radius).toHaveValue('5');
  await expect(page.locator('.filter-warning')).toHaveCount(0);
});
